apiVersion: v1
kind: Service
metadata:
  name: productcatalogserviceone
spec:
  selector:
    app: productcatalogserviceone
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
  type: LoadBalancer
  